version: 1.0.{build}
os: Visual Studio 2015 RC

environment:
  global:
    APPVEYOR_OS_NAME: windows
  matrix:
  #MSYS2 Building
    - platform: x86
      BUILDER: MSYS2

  #VisualStudio Building
    - platform: x86
      BUILDER : VS
      BITS: 32
    - platform: x64
      BUILDER : VS
      BITS: 64

configuration: Debug
shallow_clone: true
clone_depth: 10

init:
- set MSYS2_PATH=c:\msys64
- set CHERE_INVOKING=1
#- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -Sy pacman"'
#- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -Syuu"'
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x86" set MSYSTEM=MINGW32
- if "%BUILDER%_%PLATFORM%"=="MSYS2_x64" set MSYSTEM=MINGW64

- '%MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -S --needed unzip rsync"'

- IF "%BUILDER%"=="VS" set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- set PG_OF_PATH=%APPVEYOR_BUILD_FOLDER%\..\openFrameworks

install:
- cd ..
- git clone --depth=1 --branch=master https://github.com/openframeworks/openFrameworks
- move %APPVEYOR_PROJECT_NAME% openFrameworks\addons\%APPVEYOR_PROJECT_NAME%
- cd openFrameworks

- if "%BUILDER%"=="VS" (%MSYS2_PATH%\usr\bin\bash -lc "scripts/vs/download_libs.sh --silent")
- if "%BUILDER%"=="VS" (echo "Downloading projectGenerator from ci server")
- if "%BUILDER%"=="VS" (%MSYS2_PATH%\usr\bin\bash -lc "wget http://ci.openframeworks.cc/projectGenerator/projectGenerator-vs.zip -nv")
- if "%BUILDER%"=="VS" (%MSYS2_PATH%\usr\bin\bash -lc "unzip -qq projectGenerator-vs.zip")
- if "%BUILDER%"=="VS" (rm projectGenerator-vs.zip)
- if "%BUILDER%"=="VS" if exist addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\vs\install.sh call %MSYS2_PATH%\usr\bin\bash -lc "source addons/%APPVEYOR_PROJECT_NAME%/scripts/ci/vs/install.sh"
- if "%BUILDER%"=="VS" if exist addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\vs\install.bat call addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\vs\install.bat
- if "%BUILDER%"=="VS" if exist addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\vs\install.ps call addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\vs\install.ps
- if "%BUILDER%"=="VS" (    
    for /D %%e in (addons\%APPVEYOR_PROJECT_NAME%\example*) do (
        projectGenerator.exe addons\%APPVEYOR_PROJECT_NAME%\%%e
    )
  )

- if "%BUILDER%"=="MSYS2" (%MSYS2_PATH%\usr\bin\bash -lc "scripts/msys2/install_dependencies.sh --noconfirm")
- if "%BUILDER%"=="MSYS2" (%MSYS2_PATH%\usr\bin\bash -lc "scripts/msys2/download_libs.sh --silent")
- if "%BUILDER%"=="MSYS2" (
    for /D %%e in (addons\%APPVEYOR_PROJECT_NAME%\example*) do (
        copy scripts\templates\msys2\Makefile %%e\Makefile && 
        copy scripts\templates\msys2\config.make %%e\config.make
    )
  )
- if "%BUILDER%"=="MSYS2" ( if exist addons\%APPVEYOR_PROJECT_NAME%\scripts\ci\msys2\install.sh ( %MSYS2_PATH%\usr\bin\bash -lc "addons/%APPVEYOR_PROJECT_NAME%/scripts/ci/msys2/install.sh" ) )

build_script:
- if "%BUILDER%"=="MSYS2" (    
    for /D %%e in (addons\%APPVEYOR_PROJECT_NAME%\example*) do (
        %MSYS2_PATH%\usr\bin\bash -lc "make -C addons/%APPVEYOR_PROJECT_NAME%/%%~ne Debug"
    )
  )
- if "%BUILDER%"=="VS" (
    msbuild libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj  /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" &&
    for /D %%e in (addons\%APPVEYOR_PROJECT_NAME%\example*) do (
        msbuild %%e/%%~ne.vcxproj  /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    )
 )  

